# Generated by Django 5.1.7 on 2025-03-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
